# ASCAD Dataset

In [33]:
import numpy as np
import h5py

In [34]:
filename = "/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/ASCAD_F_Value/experiment_value/ascad-fixed.h5"
#filename = "/home/gchiari/Documents/ASCAD_data/ASCAD_databases/ASCAD.h5"
h5 = h5py.File(filename,'r')

In [40]:
h5.keys()

<KeysViewHDF5 ['Attack_traces', 'Profiling_traces']>

In [44]:
h5['Attack_traces'].keys()

<KeysViewHDF5 ['labels', 'metadata', 'traces']>

In [48]:
#traces = h5['Profiling_traces']['traces'][()]
#print(traces.shape)
h5['Attack_traces']['metadata'].dtype

dtype([('plaintext', 'u1', (16,)), ('ciphertext', 'u1', (16,)), ('key', 'u1', (16,)), ('masks', 'u1', (16,)), ('desync', '<u4', (1,))])

In [37]:
arr = h5['Attack_traces']['metadata'][()]
print(h5['Attack_traces']['metadata'])
print(arr)
print(arr.dtype)

<HDF5 dataset "metadata": shape (10000,), type "|V68">
[([ 31, 172, 170, 167, 237,  34, 191,  94, 192, 195,  85, 125, 149,  46, 115, 121], [162,  37, 213,  18, 216,  58,  16,  67, 197, 193, 162, 176,  28,  84, 140,  38], [ 77, 251, 224, 242, 114,  33, 254,  16, 167, 141,  74, 220, 142,  73,   4, 105], [161, 165, 119, 180, 191, 232,  52,  24, 197,   7,  58,  87, 180,  44,  10, 121], [0])
 ([145, 254, 116, 244, 139,  35,  15, 167, 204,  61, 154, 225,  58,  66, 234, 241], [ 49,  97, 182, 105, 120,  52,  71, 180, 175,  43,  58,  91,  27, 237, 110,  98], [ 77, 251, 224, 242, 114,  33, 254,  16, 167, 141,  74, 220, 142,  73,   4, 105], [206,  58, 131,  40,  29, 103,  17, 227,  65, 204, 190, 227, 158, 100, 125, 187], [0])
 ([255,  73, 174, 223, 213,  31,  55, 115,  86,  66,  64, 168,  15, 141, 186,  70], [196, 159, 166, 229, 125,  52,  22,  95,  99, 199, 124, 114, 147,  89,  61, 244], [ 77, 251, 224, 242, 114,  33, 254,  16, 167, 141,  74, 220, 142,  73,   4, 105], [153, 214, 245, 211, 141, 2

In [ ]:
#print(arr[0]['key'])
#print(arr[1]['key'])
#print(arr[2]['key'])
#print(arr[-1]['key'])
#print(arr.dtype)

In [38]:
#keys = []
#for id in range(len(arr)):
#    keys.append(arr[id]['key'])
key = arr[0]['key']
print(key)
np.save("/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/ASCAD_F_Value/experiment_value/key.npy", key)

[ 77 251 224 242 114  33 254  16 167 141  74 220 142  73   4 105]


In [42]:
from metaqnn.attack.utils import generate_precomputed_values_file

plaintexts = []
for p in range(len(arr)):
    plaintexts.append(arr[p]['plaintext'])

generate_precomputed_values_file(plaintext=np.array(plaintexts), byte=2, save_folder="/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/ASCAD_F_Value/experiment_value")

TypeError: vectorized_unmask_sbox() missing 6 required positional arguments: 'trace_i', 'key_byte', 'plaintext', 'byte_i', 'mask', and 'offset'

In [32]:
h5.close()

In [110]:
key = np.array([77, 251, 224, 242, 114,  33, 254,  16, 167, 141,  74, 220, 142,  73,   4, 105])
rank_array = np.array([-1.59544194, -1.27893078, -2.1771462,  -1.27893078, -1.52196217, -1.27893078,
 -2.1771462,  -1.27893078, -1.27893078, -1.27893078, -1.27893078, -1.59544194,
 -1.27893078, -1.59544194, -1.27893078, -1.52196217, -1.52196217, -1.27893078,
 -1.59544194, -1.59544194, -1.52196217, -1.52196217, -1.27893078, -1.59544194,
 -1.59544194, -2.1771462 , -2.24950409, -2.24950409, -1.27893078, -1.52196217,
 -1.52196217, -1.59544194, -3.39063549, -2.24950409, -1.27893078, -1.52196217,
 -1.52196217, -1.27893078, -1.27893078, -1.52196217, -1.59544194, -1.27893078,
 -1.52196217, -1.27893078, -2.24950409, -1.59544194, -1.52196217, -1.27893078,
 -1.59544194, -2.1771462 , -1.59544194, -1.59544194, -1.27893078, -1.27893078,
 -1.27893078, -2.24950409, -1.59544194, -2.24950409, -1.52196217, -3.39063549,
 -1.59544194, -1.59544194, -1.59544194, -1.59544194, -1.52196217, -1.59544194,
 -1.52196217, -1.59544194, -1.52196217, -2.1771462 , -1.52196217, -1.59544194,
 -1.27893078, -2.24950409, -1.52196217, -2.1771462 , -1.52196217, -1.59544194,
 -2.24950409, -1.52196217, -2.1771462 , -1.59544194, -1.52196217, -2.1771462,
 -2.24950409, -1.27893078, -2.1771462 , -1.59544194, -2.24950409, -2.24950409,
 -1.59544194, -2.24950409, -1.52196217, -1.52196217, -2.24950409, -2.24950409,
 -1.52196217, -1.27893078, -1.27893078, -1.59544194, -1.59544194, -1.27893078,
 -1.52196217, -1.59544194, -1.27893078, -2.24950409, -2.24950409, -1.59544194,
 -2.24950409, -1.27893078, -1.59544194, -1.59544194, -3.19586277, -1.52196217,
 -1.52196217, -1.27893078, -1.52196217, -1.52196217, -1.27893078, -1.27893078,
 -1.27893078, -1.27893078, -1.52196217, -1.27893078, -1.52196217, -1.52196217,
 -1.59544194, -2.1771462 , -2.24950409, -1.52196217, -1.52196217, -1.59544194,
 -1.52196217, -1.52196217, -1.52196217, -1.59544194, -2.24950409, -1.27893078,
 -1.52196217, -1.27893078, -1.59544194, -1.59544194, -1.59544194, -2.24950409,
 -2.1771462 , -1.59544194, -1.59544194, -1.59544194, -1.27893078, -2.1771462,
 -1.52196217, -1.27893078, -1.52196217, -1.27893078, -2.1771462 , -3.19586277,
 -2.1771462 , -5.74402046, -1.27893078, -1.27893078, -1.59544194, -2.1771462,
 -1.27893078, -2.24950409, -3.39063549, -3.19586277, -2.1771462  ,-1.59544194,
 -1.59544194, -1.27893078, -1.27893078, -1.59544194, -3.39063549, -1.27893078,
 -3.39063549, -1.59544194, -1.27893078, -2.1771462 , -5.53993702, -3.19586277,
 -2.24950409, -1.52196217, -1.52196217, -1.52196217, -2.1771462 , -1.59544194,
 -1.52196217, -1.59544194, -1.52196217, -3.19586277, -1.27893078, -1.59544194,
 -1.52196217, -1.52196217, -2.1771462 , -3.39063549, -1.27893078, -1.52196217,
 -3.19586277, -2.24950409, -1.27893078, -2.1771462 , -1.52196217, -1.52196217,
 -2.1771462 , -2.1771462,  -1.52196217, -1.27893078, -2.24950409, -1.27893078,
 -1.59544194, -1.27893078, -2.1771462 , -1.59544194, -1.27893078, -1.52196217,
 -1.27893078, -1.27893078, -1.27893078, -2.1771462 , -2.1771462 , -1.27893078,
 -2.24950409, -1.27893078, -1.59544194, -1.59544194, -1.27893078, -1.27893078,
 -1.52196217, -1.52196217, -1.27893078, -1.59544194, -1.27893078, -3.39063549,
 -2.1771462,  -1.27893078, -1.59544194, -1.27893078, -3.39063549, -2.1771462,
 -1.52196217, -1.27893078, -1.27893078, -2.1771462 , -1.27893078, -3.19586277,
 -2.24950409, -1.59544194, -1.27893078, -2.24950409, -1.27893078, -2.24950409,
 -1.27893078, -1.59544194, -1.52196217, -3.19586277])

#key_val = rank_array[key]
key_val = rank_array[0]
print(key_val)

-1.59544194


In [103]:
sorted_rank_array = np.sort(rank_array)[::-1]
print(sorted_rank_array)
#print(len(sorted_rank_array))

[-1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078
 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078
 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078
 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078
 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078
 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078
 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078
 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078
 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078
 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078
 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.27893078
 -1.27893078 -1.27893078 -1.27893078 -1.27893078 -1.52196217 -1.52196217
 -1.52196217 -1.52196217 -1.52196217 -1.52196217 -1.52196217 -1.52196217
 -1.52196217 -1.52196217 -1.52196217 -1.52196217 -1

In [86]:
new_key = key_val.reshape(len(key_val), 1)
print(new_key)

[[-1.59544194]
 [-2.24950409]
 [-1.59544194]
 [-1.27893078]
 [-1.52196217]
 [-2.24950409]
 [-1.52196217]
 [-1.52196217]
 [-1.59544194]
 [-1.59544194]
 [-1.52196217]
 [-2.1771462 ]
 [-1.59544194]
 [-2.24950409]
 [-1.52196217]
 [-2.24950409]]


In [112]:
np.where(sorted_rank_array == key_val)[0][0]

126

# DFS

In [1]:
import numpy as np
import h5py

In [2]:
root = '/work_extra/dgalli/dataset/TCHES/dataset_100/'
test_meta = np.load(root+"test_meta.npy")
test_targets = np.load(root+"test_targets.npy")
test_windows = np.load(root+"test_windows.npy")

train_meta = np.load(root+"train_meta.npy")
train_targets = np.load(root+"train_targets.npy")
train_windows = np.load(root+"train_windows.npy")

valid_meta = np.load(root+"valid_meta.npy")
valid_targets = np.load(root+"valid_targets.npy")
valid_windows = np.load(root+"valid_windows.npy")

In [3]:
print(test_meta.shape)
print(test_targets.shape)
print(test_windows.shape)
print('\n')
print(train_meta.shape)
print(train_targets.shape)
print(train_windows.shape)
print('\n')
print(valid_meta.shape)
print(valid_targets.shape)
print(valid_windows.shape)

(12800, 2)
(12800, 1)
(12800, 2570)


(102400, 2)
(102400, 1)
(102400, 2570)


(12800, 2)
(12800, 1)
(12800, 2570)


In [4]:
print(test_meta[0])  #(primo byte plaintext, primo byte key) -- key cambia ogni 50
print(test_meta[50])

[225  51]
[159  44]


In [7]:
profiling_traces = np.concatenate((train_windows, valid_windows))
profiling_targets = np.concatenate((train_targets, valid_targets))

with h5py.File('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/DFS/experiment_value/dfs.h5', 'w') as hf:
    #h5_test_meta = hf.create_dataset('/Attack_traces/metadata', data=test_meta, shape=(12800, 2), compression='gzip', chunks=True)
    h5_test_targets = hf.create_dataset('/Attack_traces/labels', data=test_targets, shape=(12800, 1), compression='gzip', chunks=True)
    h5_test_windows = hf.create_dataset('/Attack_traces/traces', data=test_windows, shape=(12800, 2570), compression='gzip', chunks=True)

    h5_profiling_targets = hf.create_dataset('/Profiling_traces/labels', data=profiling_targets, shape=profiling_targets.shape, compression='gzip', chunks=True)
    h5_profiling_traces = hf.create_dataset('/Profiling_traces/traces', data=profiling_traces, shape=profiling_traces.shape, compression='gzip', chunks=True)


In [10]:
#h5 = h5py.File("/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/test.h5", 'r')
#h5["Attack_traces/metadata"]
#print(h5["/Profiling_traces/traces"])
test_targets[5]

array([46])

In [5]:
key = [] #np.load("/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/ASCAD_F_Value/experiment_value/key.npy")
for i in range(test_meta.shape[0]):
    key.append(test_meta[i][1])
    
data_root = "data/DFS/experiment_value/"
np.save(data_root+"dfs_key.npy", key)

# FreeRTOS 1000

In [8]:
import numpy as np
from matplotlib import pyplot as plt

In [2]:
test_meta = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_1000/test_meta.npy")
test_targets = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_1000/test_targets.npy")
test_windows = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_1000/test_windows.npy")

#train_meta = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_1000/train_meta.npy")
#train_targets = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_1000/train_targets.npy")
#train_windows = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_1000/train_windows.npy")

valid_meta = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_1000/valid_meta.npy")
valid_targets = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_1000/valid_targets.npy")
valid_windows = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_1000/valid_windows.npy")

In [3]:
print(test_meta.shape)
print(test_targets.shape)
print(test_windows.shape)
print('\n')
print(train_meta.shape)
print(train_targets.shape)
print(train_windows.shape)
print('\n')
print(valid_meta.shape)
print(valid_targets.shape)
print(valid_windows.shape)

(26112, 2)
(26112, 1)
(26112, 474)


(209920, 2)
(209920, 1)
(209920, 474)


(26112, 2)
(26112, 1)
(26112, 474)


In [4]:
print(test_meta[0])  #(primo byte plaintext, primo byte key) -- key cambia ogni 102
print(test_meta[102])

[ 87 167]
[74  4]


In [ ]:
'''profiling_traces = np.concatenate((train_windows, valid_windows))
profiling_targets = np.concatenate((train_targets, valid_targets))

with h5py.File('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS1000/experiment_value/freertos1000.h5', 'w') as hf:
    #h5_test_meta = hf.create_dataset('/Attack_traces/metadata', data=test_meta, shape=(12800, 2), compression='gzip', chunks=True)
    h5_test_targets = hf.create_dataset('/Attack_traces/labels', data=test_targets, shape=(26112, 1), compression='gzip', chunks=True)
    h5_test_windows = hf.create_dataset('/Attack_traces/traces', data=test_windows, shape=(26112, 474), compression='gzip', chunks=True)

    h5_profiling_targets = hf.create_dataset('/Profiling_traces/labels', data=profiling_targets, shape=profiling_targets.shape, compression='gzip', chunks=True)
    h5_profiling_traces = hf.create_dataset('/Profiling_traces/traces', data=profiling_traces, shape=profiling_traces.shape, compression='gzip', chunks=True)'''

profiling_traces = np.concatenate((train_windows, valid_windows))
profiling_targets = np.concatenate((train_targets, valid_targets))

np.save('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS1000/experiment_value/profiling_traces.npy', profiling_traces)
np.save('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS1000/experiment_value/profiling_targets.npy', profiling_targets)

np.save('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS1000/experiment_value/attack_traces.npy', test_windows)
np.save('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS1000/experiment_value/attack_targets.npy', test_targets)


In [8]:
key = []
for i in range(test_meta.shape[0]):
    key.append(test_meta[i][1])

np.save("data/FreeRTOS1000/experiment_value/freertos1000_key.npy", key)

In [9]:
from metaqnn.attack.utils import generate_precomputed_values_file

plaintexts = []
for i in range(test_meta.shape[0]):
    plaintexts.append(test_meta[i][0])

generate_precomputed_values_file(plaintext=np.array(plaintexts), byte=0, save_folder="data/FreeRTOS1000/experiment_value/")

array([[ 91, 177, 252, ..., 172, 211, 194],
       [126,  61, 196, ..., 245, 146, 157],
       [182, 188,  33, ...,  95,  23,  68],
       ...,
       [160,  90, 110, ..., 244,  86, 108],
       [ 61, 126, 167, ...,  56, 157, 146],
       [206,  85,  40, ..., 130, 201, 125]])

# FreeRTOS 100

In [1]:
import numpy as np
import h5py

In [11]:
test_meta = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_100/test_meta.npy",mmap_mode='r')
test_targets = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_100/test_targets.npy",mmap_mode='r')
test_windows = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_100/test_windows.npy",mmap_mode='r')

train_meta = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_100/train_meta.npy",mmap_mode='r')
train_targets = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_100/train_targets.npy",mmap_mode='r')
train_windows = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_100/train_windows.npy",mmap_mode='r')

valid_meta = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_100/valid_meta.npy",mmap_mode='r')
valid_targets = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_100/valid_targets.npy",mmap_mode='r')
valid_windows = np.load("/work_extra/dgalli/dataset/FreeRTOS/8keys/dataset_100/valid_windows.npy",mmap_mode='r')

In [3]:
print(test_meta.shape)
print(test_targets.shape)
print(test_windows.shape)
print('\n')
print(train_meta.shape)
print(train_targets.shape)
print(train_windows.shape)
print('\n')
print(valid_meta.shape)
print(valid_targets.shape)
print(valid_windows.shape)

#DIM_TRAIN = 104_960
DIM_TEST = 26_112

(26112, 2)
(26112, 1)
(26112, 5192)


(209920, 2)
(209920, 1)
(209920, 5192)


(26112, 2)
(26112, 1)
(26112, 5192)


In [4]:
print(test_meta[0])  #(primo byte plaintext, primo byte key) -- key cambia ogni 102
print(test_meta[102])
print(train_windows.dtype)

[ 87 167]
[74  4]
float32


In [3]:
import psutil
 
print('RAM memory % used:', psutil.virtual_memory()[2])
profiling_traces = np.concatenate((train_windows, valid_windows))
profiling_targets = np.concatenate((train_targets, valid_targets))
print('RAM memory % used:', psutil.virtual_memory()[2])
#np.save('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS100/experiment_value/profiling_traces.npy', profiling_traces)
#np.save('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS100/experiment_value/profiling_targets.npy', profiling_targets)
#
#np.save('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS100/experiment_value/attack_traces.npy', test_windows)
#np.save('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS100/experiment_value/attack_targets.npy', test_targets)

RAM memory % used: 38.4


TypeError: append() missing 1 required positional argument: 'values'

In [66]:
#profiling_traces = np.concatenate((train_windows, valid_windows))
#profiling_targets = np.concatenate((train_targets, valid_targets))

#with h5py.File('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS100/experiment_value/freertos100.h5', 'w') as hf:
    #h5_test_meta = hf.create_dataset('/Attack_traces/metadata', data=test_meta, shape=(12800, 2), compression='gzip', chunks=True)
#    h5_test_targets = hf.create_dataset('/Attack_traces/labels', data=test_targets, shape=(26112, 1), compression='gzip', chunks=True)
#    h5_test_windows = hf.create_dataset('/Attack_traces/traces', data=test_windows, shape=(26112, 5192), compression='gzip', chunks=True)

#    h5_profiling_targets = hf.create_dataset('/Profiling_traces/labels', data=profiling_targets, shape=profiling_targets.shape, compression='gzip', chunks=True)
#    h5_profiling_traces = hf.create_dataset('/Profiling_traces/traces', data=profiling_traces, shape=profiling_traces.shape, compression='gzip', chunks=True)


In [5]:
key = []
#for i in range(test_meta.shape[0]):
for i in range(DIM_TEST):
    key.append(test_meta[i][1])

np.save("data/FreeRTOS100/experiment_value/freertos100_key.npy", key)

In [6]:
from metaqnn.attack.utils import generate_precomputed_values_file

plaintexts = []
#for i in range(test_meta.shape[0]):
for i in range(DIM_TEST):
    plaintexts.append(test_meta[i][0])

generate_precomputed_values_file(plaintext=np.array(plaintexts), byte=0, save_folder="data/FreeRTOS100/experiment_value/")

array([[ 91, 177, 252, ..., 172, 211, 194],
       [126,  61, 196, ..., 245, 146, 157],
       [182, 188,  33, ...,  95,  23,  68],
       ...,
       [160,  90, 110, ..., 244,  86, 108],
       [ 61, 126, 167, ...,  56, 157, 146],
       [206,  85,  40, ..., 130, 201, 125]])

# Rabbit 1000

In [1]:
import numpy as np

In [2]:
root = "/work_extra/dgalli/dataset/rabbit/dataset_1000/"
test_meta = np.load(root+"test_meta.npy", mmap_mode='r')
test_targets = np.load(root+"test_targets.npy",mmap_mode='r')
test_windows = np.load(root+"test_windows.npy",mmap_mode='r')

train_meta = np.load(root+"train_meta.npy",mmap_mode='r')
train_targets = np.load(root+"train_targets.npy",mmap_mode='r')
train_windows = np.load(root+"train_windows.npy",mmap_mode='r')

valid_meta = np.load(root+"valid_meta.npy",mmap_mode='r')
valid_targets = np.load(root+"valid_targets.npy",mmap_mode='r')
valid_windows = np.load(root+"valid_windows.npy",mmap_mode='r')

In [13]:
print(test_meta.shape)
print(test_targets.shape)
print(test_windows.shape)
print('\n')
print(train_meta.shape)
print(train_targets.shape)
print(train_windows.shape)
print('\n')
print(valid_meta.shape)
print(valid_targets.shape)
print(valid_windows.shape)

DIM_TEST = 25600

(25600, 2)
(25600, 1)
(25600, 80)


(204800, 2)
(204800, 1)
(204800, 80)


(25600, 2)
(25600, 1)
(25600, 80)


In [7]:
print(test_meta[0])  #(primo byte plaintext, primo byte key) -- key cambia ogni 102
print(test_meta[100])
print(test_meta[200])
print(train_windows.dtype)

[ 55 119]
[158 146]
[229 120]
float32


In [3]:
# Importing the library
import psutil
 
# Getting % usage of virtual_memory ( 3rd field)
print('RAM memory % used:', psutil.virtual_memory()[2])

profiling_traces = np.concatenate((train_windows, valid_windows))
profiling_targets = np.concatenate((train_targets, valid_targets))

print('RAM memory % used:', psutil.virtual_memory()[2])

#np.save('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS100/experiment_value/profiling_traces.npy', profiling_traces)
#np.save('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS100/experiment_value/profiling_targets.npy', profiling_targets)
#
#np.save('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS100/experiment_value/attack_traces.npy', test_windows)
#np.save('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS100/experiment_value/attack_targets.npy', test_targets)

RAM memory % used: 38.4
RAM memory % used: 38.5


In [16]:
key = []
for i in range(DIM_TEST):
    key.append(test_meta[i][1])
    
data_root = "data/rabbit_1000/experiment_value/"
np.save(data_root+"rabbit1000_key.npy", key)

In [17]:
from metaqnn.attack.utils import generate_precomputed_values_file

plaintexts = []
#for i in range(test_meta.shape[0]):
for i in range(DIM_TEST):
    plaintexts.append(test_meta[i][0])

generate_precomputed_values_file(plaintext=np.array(plaintexts), byte=0, save_folder=data_root)

array([[154,   5, 150, ..., 116, 221, 232],
       [ 34,  42, 144, ..., 249,   2, 127],
       [  5, 154,  24, ...,  31, 232, 221],
       ...,
       [233, 135,  30, ...,  71,  89, 250],
       [234, 244,  86, ...,  90, 110,  27],
       [211, 194,  98, ...,  32,  91, 177]])

# Rabbit 100

In [4]:
import numpy as np

In [5]:
root = "/work_extra/dgalli/dataset/rabbit/dataset_10/"
test_meta = np.load(root+"test_meta.npy", mmap_mode='r')
test_targets = np.load(root+"test_targets.npy",mmap_mode='r')
test_windows = np.load(root+"test_windows.npy",mmap_mode='r')

train_meta = np.load(root+"train_meta.npy",mmap_mode='r')
train_targets = np.load(root+"train_targets.npy",mmap_mode='r')
train_windows = np.load(root+"train_windows.npy",mmap_mode='r')

valid_meta = np.load(root+"valid_meta.npy",mmap_mode='r')
valid_targets = np.load(root+"valid_targets.npy",mmap_mode='r')
valid_windows = np.load(root+"valid_windows.npy",mmap_mode='r')

In [8]:
print(test_meta.shape)
print(test_targets.shape)
print(test_windows.shape)
print('\n')
print(train_meta.shape)
print(train_targets.shape)
print(train_windows.shape)
print('\n')
print(valid_meta.shape)
print(valid_targets.shape)
print(valid_windows.shape)

DIM_TEST = 25600

(25600, 2)
(25600, 1)
(25600, 13044)


(204800, 2)
(204800, 1)
(204800, 13044)


(25600, 2)
(25600, 1)
(25600, 13044)


In [4]:
print(test_meta[0])  #(primo byte plaintext, primo byte key) -- key cambia ogni 102
print(test_meta[100])
print(test_meta[200])
print(train_windows.dtype)

[ 55 119]
[158 146]
[229 120]
float32


In [ ]:
# Importing the library
import psutil
 
# Getting % usage of virtual_memory ( 3rd field)
print('RAM memory % used:', psutil.virtual_memory()[2])

profiling_traces = np.concatenate((train_windows, valid_windows))
profiling_targets = np.concatenate((train_targets, valid_targets))

print('RAM memory % used:', psutil.virtual_memory()[2])

#np.save('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS100/experiment_value/profiling_traces.npy', profiling_traces)
#np.save('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS100/experiment_value/profiling_targets.npy', profiling_targets)
#
#np.save('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS100/experiment_value/attack_traces.npy', test_windows)
#np.save('/home/gchiari/Documents/Reinforcement-Learning-for-SCA-main/data/FreeRTOS100/experiment_value/attack_targets.npy', test_targets)

In [9]:
key = []
for i in range(DIM_TEST):
    key.append(test_meta[i][1])
    
data_root = "data/rabbit_10/experiment_value/"
np.save(data_root+"rabbit10_key.npy", key)

In [10]:
from metaqnn.attack.utils import generate_precomputed_values_file

plaintexts = []
#for i in range(test_meta.shape[0]):
for i in range(DIM_TEST):
    plaintexts.append(test_meta[i][0])

generate_precomputed_values_file(plaintext=np.array(plaintexts), byte=0, save_folder=data_root)

array([[154,   5, 150, ..., 116, 221, 232],
       [ 34,  42, 144, ..., 249,   2, 127],
       [  5, 154,  24, ...,  31, 232, 221],
       ...,
       [233, 135,  30, ...,  71,  89, 250],
       [234, 244,  86, ...,  90, 110,  27],
       [211, 194,  98, ...,  32,  91, 177]])